#!/usr/bin/bash

if [[ ! -x "${SDK}/bin/pi" ]]; then
	workshopctl set-health --code="pi-not-installed" error "Pi CLI not installed."
	exit 0
fi

if ! sudo -u workshop --login which pi >/dev/null 2>&1; then
	workshopctl set-health --code="pi-not-in-path" error "Pi CLI not available on the \$PATH."
	exit 0
fi

workshopctl set-health okay
